### ISSUE TITLE
Scan doesn't stops when IP not found

### ISSUE THREAD

**Issue by Splint3r7** [projectdiscovery/naabu#166] opened 2021-05-07 23:14 UTC
**Description:**

Naabu full port scanning is not stopping when the IP is not found error occurs. It keeps scanning, the expected results from the scan if IP is not found the scan should stop. not sure if I'm missing something here but that's happening on all of my machines.

*OS:*

macOS
Kali Linux
Ubuntu 18

**To Reproduce**
Command:

```
./naabu-linux-amd64 -p - -host asdasdasdasdasda.com -rate 50000 -v -retries 0 -stats -timeout 1
```

<img width="1017" alt="Screenshot 2021-05-08 at 4 09 32 AM" src="https://user-images.githubusercontent.com/26146246/117516790-7ca30f80-afb3-11eb-9dc6-11309286b4fe.png">

**Comment by Splint3r7** [comment] 2021-05-07 23:37
23 mins passed still scanning:

![Uploading Screenshot 2021-05-08 at 4.36.58 AM.png…]()

**Comment by ehsandeep** [comment] 2021-05-08 09:31
This is a duplicate of https://github.com/projectdiscovery/naabu/issues/123 and fixed in the development version.

**Comment by ehsandeep** [comment] 2021-05-18 14:03
Closing as this is known and fixed in the dev version, in case you wanted to use dev version, soon we will create new release of naabu

```
GO111MODULE=on go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu@dev
```

**Closed by ehsandeep** 2021-05-18 14:03 UTC
Labels: Status: Completed, Type: Bug, duplicate
