### ISSUE TITLE
Statistical inaccuracy

### ISSUE THREAD

**Issue by zlgxzswjy** [projectdiscovery/naabu#1113] opened 2024-06-12 07:47 UTC
### Current Behavior:
I made an ip` x.x.x.x` using-host and enabled the`-stats -mp 63636` parameter，But when I request `http://localhost:63636/metrics` , the json returned prompts me that the number of `"hosts": 2`

### Expected Behavior:
Number of hosts should be 1

### Steps To Reproduce:

Example: steps to reproduce the behavior:
1. Run 'naabu -host 47.101.211.147 -p - -stats -mp 63636'
2. curl http://localhost:63636/metrics|jq

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   169  100   169    0     0  19580      0 --:--:-- --:--:-- --:--:-- 21125
{
  "total": 393210,
  "packets": 3500,
  "hosts": 2,
  "retries": 3,
  "errors": 0,
  "startedAt": "2024-06-12T15:45:55.953068423+08:00",
  "hosts_with_port": 0,
  "ports": 65535,
  "duration": "0:00:07"
}

**Comment by zlgxzswjy** [comment] 2024-06-12 08:32
When I add`-Pn`, The command becomes: `naabu -host 47.101.211.147-Pn -p - -stats -mp 63636`。the statistics are correct.
So is it just a statistical error, or are there really a lot of duplicate requests?

**Comment by dogancanbakir** [comment] 2024-06-12 10:59
Can you retry with `dev` branch? Thanks

```
go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@dev
```

**Comment by Mzack9999** [comment] 2024-06-12 14:06
Just guessing, but that's possible that statistics are wrongly incremented during host-discovery phase. Whereas if we have both service-discovery + port-scan probably we should consider only portscan as relevant, or split the statistics in two parts for the respective phases.

**Comment by zlgxzswjy** [comment] 2024-06-14 04:13
> Can you retry with `dev` branch? Thanks
> 
> ```
> go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@dev
> ```

I try this `dev` branch with the same commad,the json also returned prompts me : `"hosts": 2`

**Comment by dogancanbakir** [comment] 2024-06-25 10:59
I couldn't repro this issue - used the `dev` branch for testing.

```console
$ go run . -host 47.101.211.147 -p - -stats -mp 63636

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

                projectdiscovery.io

[INF] Current naabu version 2.3.1 (latest)
[INF] Running CONNECT scan with non root privileges
Target: 47.101.211.147/32, Target Count: 1
47.101.211.147:32080
47.101.211.147:43080
```

```console
$ curl -s http://localhost:63636/metrics | jq .hosts
1
```

**Comment by zlgxzswjy** [comment] 2024-07-01 06:50
This may be a problem with my cloud service provider. I scan the same ip on my local arch linux,hosts is indeed 1, but when placed on my Aliyun ECS, hosts is still 3 or 2.

**Comment by dogancanbakir** [comment] 2024-07-31 11:23
FYI: I still can't repro this but I'll leave it open for a while to see if someone else is experiencing it.

**Comment by Mzack9999** [comment] 2024-09-03 17:29
@zlgxzswjy I'm also unable to reproduce. If you can provide more info about the machine from where you are performing the scan (as it seems the cloud environment is different from local), we will try to have another look and fix. I'm closing the issue for the time being as we are unable to reproduce.

**Closed by Mzack9999** 2024-09-03 17:29 UTC
Labels: Type: Bug
