### ISSUE TITLE
getting error while scaniing the ip 

### ISSUE THREAD

**Issue by RizwanSiDdiqu1** [projectdiscovery/naabu#632] opened 2023-03-31 06:51 UTC
### Steps To Reproduce:

Example: steps to reproduce the behavior:

```
root@localhost:~/temp# naabu -host 96.99.229.151

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v2.1.1

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
[INF] Running host discovery scan
[INF] Running SYN scan with CAP_NET_RAW privileges
[FTL] Could not run enumeration: no valid ipv4 or ipv6 targets were found
```

But when I run the same IP with rustscan it gives me the result

```
root@localhost:~/temp# rustscan -a 96.102.223.104 -r 1-65535
.----. .-. .-. .----..---.  .----. .---.   .--.  .-. .-.
| {}  }| { } |{ {__ {_   _}{ {__  /  ___} / {} \ |  `| |
| .-. \| {_} |.-._} } | |  .-._} }\     }/  /\  \| |\  |
`-' `-'`-----'`----'  `-'  `----'  `---' `-'  `-'`-' `-'
The Modern Day Port Scanner.
________________________________________
: https://discord.gg/GFrQsGy           :
: https://github.com/RustScan/RustScan :
 --------------------------------------
Real hackers hack time ⌛

[~] The config file is expected to be at "/home/rustscan/.rustscan.toml"
[~] File limit higher than batch size. Can increase speed by increasing batch size '-b 1048476'.
Open 96.102.223.104:443
[~] Starting Script(s)
[~] Starting Nmap 7.80 ( https://nmap.org ) at 2023-03-31 06:40 UTC
Initiating Ping Scan at 06:40
Scanning 96.102.223.104 [2 ports]
Completed Ping Scan at 06:40, 0.28s elapsed (1 total hosts)
Initiating Parallel DNS resolution of 1 host. at 06:40
Completed Parallel DNS resolution of 1 host. at 06:40, 0.00s elapsed
DNS resolution of 1 IPs took 0.00s. Mode: Async [#: 3, OK: 0, NX: 1, DR: 0, SF: 0, TR: 1, CN: 0]
Initiating Connect Scan at 06:40
Scanning 96.102.223.104 [1 port]
Discovered open port 443/tcp on 96.102.223.104
Completed Connect Scan at 06:40, 0.27s elapsed (1 total ports)
Nmap scan report for 96.102.223.104
Host is up, received syn-ack (0.28s latency).
Scanned at 2023-03-31 06:40:18 UTC for 1s

PORT    STATE SERVICE REASON
443/tcp open  https   syn-ack

Read data files from: /usr/bin/../share/nmap
Nmap done: 1 IP address (1 host up) scanned in 0.64 seconds
```

**Comment by ehsandeep** [comment] 2023-03-31 12:10
@RizwanSiDdiqu1, you are using outdated version of naabu, make sure to update to latest one.

```console
naabu -host 96.99.229.151

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

		projectdiscovery.io

[INF] Current naabu version 2.1.5 (latest)
[INF] Running CONNECT scan with non root privileges
[INF] Found 1 ports on host 96.99.229.151 (96.99.229.151)
96.99.229.151:443
```

**Comment by hosainxade** [comment] 2023-05-29 07:35
> @RizwanSiDdiqu1, you are using outdated version of naabu, make sure to update to latest one.
> 
> ```
> naabu -host 96.99.229.151
> 
>                   __
>   ___  ___  ___ _/ /  __ __
>  / _ \/ _ \/ _ \/ _ \/ // /
> /_//_/\_,_/\_,_/_.__/\_,_/
> 
> 		projectdiscovery.io
> 
> [INF] Current naabu version 2.1.5 (latest)
> [INF] Running CONNECT scan with non root privileges
> [INF] Found 1 ports on host 96.99.229.151 (96.99.229.151)
> 96.99.229.151:443
> ```

I use latest version but i have this error!!
<img width="674" alt="Screenshot 1402-03-08 at 11 05 19" src="https://github.com/projectdiscovery/naabu/assets/127223084/f40af4cb-1604-4f46-bfc0-35eb6cfa15cb">

**Comment by mrvcoder** [comment] 2023-07-04 10:48
same !

**Comment by Mzack9999** [comment] 2023-07-04 11:33
@hosainxade @mrvcoder, Could you provide more info about how to reproduce the issue? Ideally, the verbose output of the command that is causing the error and the output of `naabu -hc would be handy as we need more info about the Operative System, execution environment (docker/VirtualBox/VPS/etc.), networking, and so on.

Thanks!

**Comment by sw33tLie** [comment] 2023-07-04 15:45
Hi, this issue can be reproduced with this host: m.gene.com

The CONNECT scan works, but the sudo-based one fails.
It's weird because it can actually find the IP, but then complains it didn't find one.
![image](https://github.com/projectdiscovery/naabu/assets/47645560/fd4cad90-7df8-4316-8424-8aefb6c003eb)

**Comment by mrvcoder** [comment] 2023-07-05 08:50
> @hosainxade @mrvcoder, Could you provide more info about how to reproduce the issue? Ideally, the verbose output of the command that is causing the error and the output of `naabu -hc would be handy as we need more info about the Operative System, execution environment (docker/VirtualBox/VPS/etc.), networking, and so on.
> 
> Thanks!

hello , this is the output of `echo $ip | naabu -p 443,80 -v -interface ens3 -hc` (the $ip which I test that ports , they are open but naabu gives"Running SYN scan with CAP_NET_RAW privileges" as last message and finishs) :

```
Version: 2.1.6
Operative System: linux
Architecture: amd64
Go Version: go1.20.3
Compiler: gc
Privileged/NET_RAW: Ok
Config file "/root/.config/naabu/config.yaml" Read => Ok
Config file "/root/.config/naabu/config.yaml" Write => Ok
TCP IPv4 connectivity to scanme.sh:80 => Ok
TCP IPv6 connectivity to scanme.sh:80 => Ok
UDP IPv4 connectivity to scanme.sh:80 => Ok
UDP IPv6 connectivity to scanme.sh:80 => Ok
```

**Comment by Mzack9999** [comment] 2023-07-10 18:43
Closing as completed as the root cause was found after investigation and two follow up tickets were created (https://github.com/projectdiscovery/naabu/issues/726 and https://github.com/projectdiscovery/naabu/issues/727)

**Closed by Mzack9999** 2023-07-10 18:43 UTC
Labels: Status: Completed, Type: Bug
