### ISSUE TITLE
mismatched hardware address sizes

### ISSUE THREAD

**Issue by galimba** [projectdiscovery/naabu#1] opened 2020-01-21 21:13 UTC
I downloaded and installed from source on kali. Tried to use `naabu` to scan a HTB machine (Mango) using the command:
`naabu -host 10.10.10.160 -v`

the result was:

```
[INF] Using IP 10.10.10.160 for enumeration
[INF] Starting scan on host 10.10.10.160 (10.10.10.160)
[WRN] Could not start scan on host 10.10.10.160 (10.10.10.160): mismatched hardware address sizes
```
then program just exits.

**Comment by Mzack9999** [comment] 2020-01-21 23:39
Hi @galimba, thanks for reaching out! 

it seems like an internal routing error due to OpenVPN virtual interface. Are you facing the same issue with any kind of ips (eg. Lan, Internet)? I will try to reproduce the issue, and implement a fix

**Comment by galimba** [comment] 2020-01-22 00:30
yeah, I thought it was because of OpenVPN... the issue only happens while I'm on a VPN, tried it on my dayjob VPN and got the same error.

**Comment by Mzack9999** [comment] 2020-01-22 01:20
I'm working on a fix that should be available shortly, scanning 10.x.x.x range seems to work properly on a fresh kali installation with active OpenVPN connection to HTB. Could you confirm if the routing table of your kali system is similar to this?

```
# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.2.2        0.0.0.0         UG    100    0        0 eth0
10.0.2.0        0.0.0.0         255.255.255.0   U     100    0        0 eth0
```

Thanks for your help!

**Comment by bsysop** [comment] 2020-01-22 02:20
Tried from VPS, but got same error

**Comment by galimba** [comment] 2020-01-22 02:35
Perhaps it's got something to do with virtualization... I'm not running kali on bare metal

![image](https://user-images.githubusercontent.com/5059808/72860733-7dbd0a00-3ca6-11ea-8a5f-b4a501f4b98f.png)

**Comment by Ice3man543** [comment] 2020-01-24 05:33
Hi @galimba @bsysop this issue should be fixed in the latest release. Let me know if that works!

**Comment by bsysop** [comment] 2020-01-24 10:53
Fix confirmed from VPS! Thanks

**Comment by bauthard** [comment] 2020-01-24 11:01
Thank you for the confirmation @bsysop, closing this issue.

**Closed by bauthard** 2020-01-24 11:01 UTC
Labels: bug
