### ISSUE TITLE
-bash: /usr/bin/naabu: No such file or directory

### ISSUE THREAD

**Issue by NoneNotNull** [projectdiscovery/naabu#42] opened 2020-06-16 14:13 UTC
linux amd64, I have moved it to /usr/bin/naabu, but error
-bash: /usr/bin/naabu: No such file or directory

**Comment by NoneNotNull** [comment] 2020-06-16 14:24
I have resolved it
apt-get install musl-dev

Why not compile it into bin

**Comment by Mzack9999** [comment] 2020-06-16 14:58
Hi @NoneNotNull - Thanks for reaching out, I think it's been a temporary issue with your environment. As the problem is resolved I'm closing the issue, let us know if you encounter any other problem

**Comment by bauthard** [comment] 2020-07-12 10:09
This is valid issue across all the FOSS projects.

**Comment by bauthard** [comment] 2020-07-12 10:10
Related issues @Mzack9999 

```
https://github.com/projectdiscovery/naabu/issues/40
https://github.com/projectdiscovery/subfinder/issues/251
https://github.com/projectdiscovery/naabu/issues/42
https://github.com/projectdiscovery/nuclei/issues/116
```

**Comment by Mzack9999** [comment] 2020-07-13 18:06
Solved in #51

**Closed by Mzack9999** 2020-07-13 18:06 UTC
Labels: Priority: High, Type: Bug
