### ISSUE TITLE
[FTL] Could not create runner: listen ip4:tcp : socket: protocol not supported naabu verion 2.1.1

### ISSUE THREAD

**Issue by Ajm41** [projectdiscovery/naabu#497] opened 2022-12-03 14:27 UTC

**Comment by Ajm41** [comment] 2022-12-03 14:27
[FTL] Could not create runner: listen ip4:tcp : socket: protocol not supported

**Comment by ehsandeep** [comment] 2022-12-03 15:39
duplicate of https://github.com/projectdiscovery/naabu/issues/495

**Closed by ehsandeep** 2022-12-03 15:39 UTC
Labels: Type: Bug
